### ISSUE TITLE
Settings crash

### ISSUE THREAD

**Issue by thatmanthere** [CreatureSurvive/shuffle#13]

**Comment by thatmanthere** [comment]
https://ghostbin.co/paste/8c386

**Comment by Tizioincognit0** [comment]
I've the same issue on my iPhone X with iOS 14.3 jailbroken with Unc0ver: https://ghostbin.co/paste/fmwcks.

**Comment by Tizioincognit0** [comment]
This issue has been fixed after the latest update of Shuffle (1.5.4).
