### ISSUE TITLE
Crashes randomly when going through tweak list

### ISSUE THREAD

**Issue by Player123099** [CreatureSurvive/shuffle#28]
Like the title says, crashes randomly when opening tweak “indexes.” I’ve not been able to pinpoint the issue or recreate it specifically but it happens a lot and i have to respring to fix my settings app.

**Comment by khal0o0** [comment]
Same here. I sent him the reports too

**Comment by Player123099** [comment]
sorry to hear that bro! i love this tweak though, switched from preference organizer over to shuffle. the dev seems really cool too.
