### ISSUE TITLE
Apps and some system apps missing under their selections

### ISSUE THREAD

**Issue by binaondrej** [CreatureSurvive/shuffle#34]
iPhone 6S, iOS 14.2, checkra1n

All *apps* and some *system apps* missing under their selections

Screenshots:
![Apps_selection](https://user-images.githubusercontent.com/26080108/102221678-b8451c00-3ee2-11eb-98c9-0ad2d90c1510.PNG)
![Settings-Shuffle](https://user-images.githubusercontent.com/26080108/102221506-88961400-3ee2-11eb-982b-b427e4127b83.PNG)

**Comment by ataberkycl** [comment]
I have same issue on ios 14.1 iphone 8 checkra1n

**Comment by binaondrej** [comment]
I use checkra1n too

**Comment by nackerr** [comment]
Also having the same issue!
