### ISSUE TITLE
can't "apply"

### ISSUE THREAD

**Issue by 3m4r5** [CreatureSurvive/shuffle#38]
the settings app crashes when tapping apply in package dylibs

[crash log](https://github.com/CreatureSurvive/shuffle/files/6528065/text.txt)

**Comment by Tizioincognit0** [comment]
I've the same issue on my iPhone X with iOS 14.3 jailbroken with Unc0ver also with other options: https://ghostbin.co/paste/o98oy.

**Comment by Tizioincognit0** [comment]
This issue has been fixed in latest update (v. 1.5.8).
