### ISSUE TITLE
Tweak settings page don't persist

### ISSUE THREAD

**Issue by xxHoBoZxx** [CreatureSurvive/shuffle#5]
If I am in a tweak settings and make a change that does not require a respring and go to SB to view the change then go back to the settings page. It reloads the settings page and not the tweak settings page. For instance with XenHTML or Springtomize 4, making a change and viewing the SB it kicks me out to the main settings page and I have to navigate back to the tweak settings page again.

I have tested it by disabling "Shuffle" and just using the main settings page to go to the tweak settings, make a change and back to settings and I am back at the tweak settings page as it should be.

My device is an iP7 on 12.1.1b3 with Unc0ver JB version 3.0.1

**Comment by xxHoBoZxx** [comment]
https://pastebin.com/9uX2Lr76

**Comment by xxHoBoZxx** [comment]
Something I should mention:
I uninstalled this and installed PreferenceOrganizer 2 and it had the same issue. I also installed SettingsCollapse and it worked (sort of), but crashed my settings page and had to uninstall it.

**Comment by CreatureSurvive** [comment]
@xxHoBoZxx I believe the issue is due to BioProtect XS being enabled for tweaks, you should be able to disable that and resolve this problem.

**Comment by xxHoBoZxx** [comment]
You are correct. I disabled the setting in BioProtect to protect the "Settings" app and all is workings now. Thanks you so much for finding out what was wrong, much appreciated man. It was driving me crazy as I really love "Shuffle".
