### ISSUE TITLE
Certain tweaks' titles header got messed up after updating to 1.6.0

### ISSUE THREAD

**Issue by Ryanizleee** [CreatureSurvive/shuffle#50]
Here's an example, when it works fine on version 1.5.9 :
![37359307-8E92-4BBD-882D-8E8AF4A81CC8](https://user-images.githubusercontent.com/21989404/145354380-f8eab720-c1ff-4fab-8c45-e2d97dced4b8.png)

And after updating to 1.6.0 it becomes like this : 
![55938E08-EEE4-4B57-8F80-3711B2634ABB](https://user-images.githubusercontent.com/21989404/145354471-36040c20-95b7-4f3a-8b8a-5726fa2e7694.png)

As stated in the title, this does not happen to every tweak.

**Comment by semvis123** [comment]
Can confirm (happens on my tweak [Sonitus](https://github.com/semvis123/Sonitus)), the height of the Cephei `HBPackageNameHeaderCell` seems to be incorrect on 1.6.0

**Comment by CreatureSurvive** [comment]
Sorry, I've not been keeping up with Jailbreak projects the last several months due to life events. I apologize it took me so long to address this issue, but I have just released v1.6.1 to resolve this.
